### ISSUE TITLE
String concat spacing standard for laravel

### ISSUE THREAD

**Issue by delta1186** [tighten/tlint#194]
@mattstauffer I am currently using the https://gist.github.com/laravel-shift/cab527923ed2a109dda047b97d53c200 file for Laravel Shift with php fixer.  Everything formats correctly except for 

```
'concat_space' => [
        'spacing' => 'none'
    ],
```
I see in tlint you all use 1 space.  I know tlint is an opinionated linter, but I am just curious if there is a consensus on the concat spacing in the Laravel community?

Thanks, Kevin

**Comment by delta1186** [comment]
https://gist.github.com/laravel-shift/cab527923ed2a109dda047b97d53c200#gistcomment-3488397

According to Jason, Laravel doesn’t use a space after a string concatenation. 

Laravel is
`$a = ‘hello,’.’world’;`

Tlint is 
`$a = ‘hello,’ . ’world’;`

Is this tighten specific or should tlint mirror Laravel in this regard?

**Comment by loganhenson** [comment]
This is the `ConcatenationSpacing` lint, which is part of the `Tighten` preset. The `Laravel` preset does not include this lint (since as you said, they do not follow that style in the Laravel codebase). The readme includes instructions for switching presets (in this case, it seems you are looking for the Laravel preset), as well as customizing to fit your own needs.

Please let me know if that doesn't answer your question!

**Comment by delta1186** [comment]
Whoops, shame on me.  I totally missed that tlint.json preset option.  Since I am currently using php-cs-fixer to format I just created a project specific config to change the format to add a space for the string concat.  

Now with that being said, I did just run a quick test on tlint with the preset set to laravel, but when I ran tlint it did not throw a message about the string concat now having extra spaces.  I have tlint installed globally and directly in project.  So I ran tlint from both locations and neither seemed to be applying the laravel preset.

```
{
    "preset": "laravel"
}
```

**Comment by loganhenson** [comment]
@delta1186 This is where the preset lists live (https://github.com/tighten/tlint/tree/b41438e90fef70e8e409e14908b640a3c61e9c9a/src/Presets)

The `ConcatenationSpacing` lint is only checks that there _is a space_, so it is only included in the `Tighten` preset.

There is not currently any linter that checks the inverse (that there _is not a space_). Likely because I we didn't know that was an explicit style for the Laravel codebase at the time. However, if it is an explicit rule, then a linter for that would be great!

**Comment by delta1186** [comment]
According to Jason, Laravel does not have a space.  

https://gist.github.com/laravel-shift/cab527923ed2a109dda047b97d53c200#gistcomment-3488397

So I would assume this is the case.  I can probably take a stab at this if you want.

**Comment by loganhenson** [comment]
Awesome @delta1186, that would be great!

**Comment by delta1186** [comment]
@loganhenson I have submitted a PR for this enhancement.  Please review and let me know if I need to do anything else. Thanks!
