### ISSUE TITLE
`File` class in current namespace mistaken for Facade alias

### ISSUE THREAD

**Issue by bakerkretzmar** [tighten/tlint#251]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/18192441/128521275-351bafde-ab2e-4a90-93d8-f0e21a1caa7b.png">

**Comment by mattstauffer** [comment]
The original goal of this lint was to avoid using the base aliased `Cache` in non-namespaced (therefore root-namespaced) PHP classes.

However, there are so few of those in modern Laravel codebases that this Lint as-is seems unhelpful.

However, Jacob and I *did* both assume it would force someone to import `Illuminate/Support/Facades/Cache` instead of `Cache`, and it's *not* doing that.

So, the proposal is to remove this lint from the Tighten default (and the Laravel one, if it's there) and create a new lint that disallows statements like `use Cache;`. 

We know this will break if someone creates an actual root-level class named the same as any Facade's imported alias; just don't do it lol 🤷🏻‍♂️ (Also, if you are doing it for some reason, you can just ignore this lint).

We would love to add this new linter to the Tighten preset but don't feel like we can do that until the next version bump.
